---
title: "Philly Parking Tickets"
author: "Jacob Rozran"
date: "March 8, 2016"
output: html_document
---

# INTRODUCTION

I few weeks ago, I stumblied across [Dylan Purcell's](https://twitter.com/dylancpurcell) 
article on [Philadelphia Parking Violations](http://data.philly.com/philly/parking/). This
 is a nice glimpse of the data, but I wanted to get a taste of it myself. I went and 
 downloaded the entire data set of  [Parking Violations in Philadelphia](https://www.opendataphilly.org/dataset/parking-violations) 
 from the [OpenDataPhilly website](http://opendataphilly.org) and came up with a few 
 questions after checking out the data: 

* How many tickets in the data set?
* What is the range of dates in the data?
* Are there missing days/data?
* What was the biggest/smallest individual fine? What were those fines for? 
Who issued those fines?
* What was the average individual fine amount?
* What day had the most/least count of fines? What is the average amount per day?
* How much $ in fines did they write each day?
* What hour of the day are the most fines issued?
* What day of the week are the most fines issued?
* What day of the month are the most fines issued?
* What state has been issued the most fines?
* Who (what individual) has been issued the most fines?
* How much does the individual with the most fines owe the city?
* How many people have been issued fines?
* What fines are issued the most/least?

And finally to the cool stuff:

* Where were the most fines? Can I see them on a heat map?
* Can I predict the amount of parking tickets by weather data and other factors using linear regression? How about using Random Forests?

```{r do_all_the_things, include=FALSE, echo=FALSE, cache=TRUE}
library(plyr)           # NEEDED TO DO SOME COOL DATA MANIPULATIONS
library(ggplot2)        # LETS ME PLOT THE TICKETS
library(ggmap, quietly = TRUE)  # LETS ME GRAB A MAP OF PHILLY TO PLOT THE TICKETS AGAINST
library(randomForest, quietly = TRUE)   # RANDOM FORESTS = PREDICTIONS... YES!

ptix <- read.csv("Parking_Violations.csv")      ## DATA FILE FROM OPENDATAPHILLY

## QUESTIONS TO ANSWER
# How many tickets are there?
numtix <- dim(ptix)[1]

# What is the range of dates in the data frame?
## CONVERT TO A DATETIME OBJECT
ptix$Issue.Date.and.Time <- as.POSIXct(strptime(as.character(ptix$Issue.Date.and.Time), 
                                                format = "%m/%d/%Y %I:%M:%S %p"))

earliest <- min(ptix$Issue.Date.and.Time)       ## EARLIEST = MINIMUM DATETIME
latest <- max(ptix$Issue.Date.and.Time)         ## LATEST = MAXIMUM DATETIME
range <- latest - earliest                      ## RANGE IS THE DIFFERENCE

# Are there missing days/data?
## CONVERT THE DATETIME TO BE A DATE ONLY
days <- as.data.frame(as.Date(ptix$Issue.Date.and.Time, format = "%m/%d/%Y"))
names(days) <- "date"                   ## NAME THE COLUMN TO SOMETHING NICE
## COUNT THE DATA BY DATE - HOW MANY TICKETS DO WE HAVE EVERY DAY
count_by_day <- ddply(days, .(date), summarize, count = length(date))

# What was the biggest/smallest fine? What were those fines for? Who issued those fines?
ptix$Fine <- gsub("\\$", "", ptix$Fine)         ## REMOVE THE '$'
ptix$Fine <- as.numeric(ptix$Fine)              ## CHANGE IT TO A NUMERIC

## GRAB THE IMPORTANT COLUMNS FOR WHEN THE FINE IS THE MAXIMUM
maxfine_tot <- ptix[ptix$Fine == max(ptix$Fine), c(1, 5, 7, 8, 9, 10)]
## GRAB THE IMPORTANT COLUMNS FOR WHEN THE FINE IS THE MINIMUM
minfine_tot <- ptix[ptix$Fine == min(ptix$Fine), c(1, 5, 7, 8, 9, 10)]
ptix$Fine[ptix$Fine == min(ptix$Fine)] <- 2000  ## CHANGING THE $1 FINES TO $2000
## GRAB THE IMPORTANT COLUMNS FOR WHEN THE FINE IS THE MINIMUM NOW
minfine_tot <- ptix[ptix$Fine == min(ptix$Fine), c(1, 5, 7, 8, 9, 10)]

# What was the average fine?
summary(ptix$Fine)

# What day had the most fines? Least fines?
## DAY WITH THE MOST FINES ISSUED
maxday <- count_by_day[count_by_day$count == max(count_by_day$count), ]
## DAY WITH THE LEAST FINES ISSUED
minday <- count_by_day[count_by_day$count == min(count_by_day$count), ]
avday <- mean(count_by_day$count)       ## CALCULATE THE MEAN

# How much $ in fines did they write each day? Average? 
ptix <- cbind(ptix, days)       ## ADD THE FORMATTED DAYS FIELD TO THE DATA FRAME
## SUMMARIZE THE SUM OF FINES PER DAY
dollars_per_day <- ddply(ptix, .(date), summarize, dols = sum(Fine))
## DAY WITH THE MOST DOLLARS OF FINES ISSUED
maxdols <- dollars_per_day[dollars_per_day$dols == max(dollars_per_day$dols), ]
## DAY WITH THE LEAST DOLLARS OF FINES ISSUED
mindols <- dollars_per_day[dollars_per_day$dols == min(dollars_per_day$dols), ]
## THE AVERAGE AMOUNT IN FINES ISSUED IN A DAY
avgdols <- mean(dollars_per_day$dols)

# What hour of the day had the most fines?
hours <- as.data.frame(strftime(ptix$Issue.Date.and.Time, format = "%H"))
names(hours) <- "hour"
count_by_hour <- ddply(hours, .(hour), summarize, count = length(hour))
maxhour <- count_by_hour$hour[count_by_hour$count == max(count_by_hour$count)]
minhour <- count_by_hour$hour[count_by_hour$count == min(count_by_hour$count)]

# What day of the week had the most fines?
wday <- as.data.frame(strftime(ptix$Issue.Date.and.Time, format = "%A"))
names(wday) <- "weekday"
count_by_wday <- ddply(wday, .(weekday), summarize, count = length(weekday))
maxwday <- count_by_wday$weekday[count_by_wday$count == max(count_by_wday$count)]
minwday <- count_by_wday$weekday[count_by_wday$count == min(count_by_wday$count)]

# What day of the month had the most fines?
mday <- as.data.frame(strftime(ptix$Issue.Date.and.Time, format = "%d"))
names(mday) <- "day_of_month"
count_by_mday <- ddply(mday, .(day_of_month), summarize, count = length(day_of_month))
maxmday <- count_by_mday$day_of_month[count_by_mday$count == max(count_by_mday$count)]
minmday <- count_by_mday$day_of_month[count_by_mday$count == min(count_by_mday$count)]

# What state has the most fines?
count_by_state <- ddply(ptix, .(State), summarize, count = length(State))
maxstate <- count_by_state[count_by_state$count == max(count_by_state$count), ]
minstate <- count_by_state[count_by_state$count == min(count_by_state$count), ]

# What is the furthest someone came to get a fine?
# Who has the most fines?
ID <- paste(ptix$State, ptix$Plate.ID, sep = "")
fines <- as.data.frame(cbind(ptix$Fine, ID))
names(fines) <- c("fine", "ID")

count_by_plate <- ddply(fines, .(ID), summarize, count = length(ID), 
                        totalFine = sum(as.numeric(fine)))

maxcount <- count_by_plate[count_by_plate$count == max(count_by_plate$count), ]

# Who paid the most in fines?
maxfine <- count_by_plate[count_by_plate$totalFine == max(count_by_plate$totalFine), ]

# How many people have been issued fines?
numpeeps <- dim(count_by_plate)[1]

```

Question                                                        | Answer
----------------------------------------------------------------|---------------------------------------------
How many tickets in the data set?                               | `r numtix`
What is the range of dates in the data?                         | `r round(range, 0)`
Are there missing days/data?                                    | Nope. 
What was the biggest individual fine?                           | $`r maxfine_tot$Fine[1]`
What was the biggest individual fine for?                       | `r as.character(maxfine_tot$Violation.Description[1])`
What was the smallest individual fine?                          | $`r minfine_tot$Fine[1]`
What was the smallest individual fine for?                      | `r as.character(minfine_tot$Violation.Description[1])`
What was the average individual fine amount?                    | $`r round(mean(ptix$Fine), 2)`
What day had the most count of violations?                      | `r maxday$date`
How many violations on that day?                                | `r maxday$count`
What day had the least count of violations?                     | `r minday$date`
How many violations on that day?                                | `r minday$count`
What is the average amount of violations per day?               | `r avday`
How much $ in fines did the city write each day on average?     | $`r round(avgdols, 2)`
What hour of the day are the most fines issued?                 | `r as.character(maxhour)`
What hour of the day are the least fines issued?                | `r as.character(minhour)`
What day of the week are the most fines issued?                 | `r as.character(maxwday)`
What day of the week are the least fines issued?                | `r as.character(minwday)`
What day of the month are the most fines issued?                | `r as.character(maxmday)`
What day of the month are the least fines issued?               | `r as.character(minmday)`
What state has been issued the most fines?                      | `r as.character(maxstate$State)`
How many violations does the individual with the most have?     | `r maxfine$count`
How much does the individual with the most fines owe the city?  | $`r maxfine$totalFine`
How many people have been issued fines?                         | `r numpeeps`
What fines are issued the most/least?                           | NEED TO FIGURE THIS OUT